version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: trex_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: trexdb
      MYSQL_USER: trex
      MYSQL_PASSWORD: trexpass
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: trex_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  dbdata:
